name: Test Install/Uninstall Cycle

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    paths:
      - 'scripts/deploy/install.ps1'
      - 'scripts/deploy/uninstall.ps1'
      - 'scripts/test/test-installation-script.ps1'
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/deploy/install.ps1'
      - 'scripts/deploy/uninstall.ps1'
      - 'scripts/test/test-installation-script.ps1'

env:
  DEV_TEAM_EMAIL: 'dev-team@example.com'
  REPO_ADMINS: 'admin@example.com'

jobs:
  test-install-uninstall-cycle:
    name: Test Complete Install/Uninstall Cycle
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
        
    - name: Verify Initial Clean State
      shell: pwsh
      run: .\scripts\test\verify-initial-clean-state.ps1 -VerboseLogging -NonInteractive
        
    - name: Test Installation Script
      shell: pwsh
      run: .\scripts\test\test-installation-script.ps1 -VerboseLogging -NonInteractive
        
    - name: Verify Installation State
      shell: pwsh
      run: .\scripts\test\verify-installation-state.ps1 -VerboseLogging -NonInteractive
        
    - name: Test Uninstallation Script
      shell: pwsh
      run: .\scripts\test\test-uninstallation-script.ps1 -VerboseLogging -NonInteractive
        
    - name: Verify Clean Uninstall State
      shell: pwsh
      run: .\scripts\test\verify-clean-uninstall-state.ps1 -VerboseLogging -NonInteractive
        
    - name: Test Remote Installation
      shell: pwsh
      run: .\scripts\test\test-remote-installation.ps1 -VerboseLogging -NonInteractive
        
    - name: Cleanup Test Environment
      shell: pwsh
      run: .\scripts\test\cleanup-test-environment.ps1 -VerboseLogging -NonInteractive
        
    - name: Generate Test Report
      shell: pwsh
      run: .\scripts\test\generate-test-report.ps1 -VerboseLogging -NonInteractive